Nightly 11 1 20
BehrRiley/network-script-data pull request #133
Opened 2020-11-02 11:45 UTC by Eutherin

2020-11-02 12:05 UTC, Eutherin commented
https://github.com/Adriftus-Studios/network-script-data/issues/192

2020-11-02 12:16 UTC, Eutherin commented
https://github.com/Adriftus-Studios/network-script-data/issues/190

2020-11-03 00:35 UTC, BehrRiley requested changes

2020-11-03 00:35 UTC, BehrRiley commented on denizen_scripts/survival/repo_link/items/backpack.dsc
> +    - determine <element[9001]>
you don't need the wrapper here
```suggestion
    - determine 9001
```

2020-11-03 00:35 UTC, BehrRiley commented on denizen_scripts/survival/repo_link/global_systems/chunk_claim_protection.dsc
> +    on player clicks *door|*_button|lever|chest|ender_chest|*_gate|crafting_table|anvil|furnace|brewing_stand|enchanting_table|*_bed|bookshelf|barrel|hopper|tnt|dispenser|dropper|stonecutter|lodeston
there's a stray pipe at the end here that would mess this up here
```suggestion
    on player clicks *door|*_button|lever|chest|ender_chest|*_gate|crafting_table|anvil|furnace|brewing_stand|enchanting_table|*_bed|bookshelf|barrel|hopper|tnt|dispenser|dropper|stonecutter|lodeston|beehive|smithing_table|lectern|grindstone|flethcing_table|cartography_table|blast_furnace|smoker|composter|loom|trappged_chest|*_shulker_box|cauldron|cake|bell|jukebox|note_block|beacon|respawn-anchor|repeater|redstone_dust|comparator|daylight_detector|tripwire_hook|end_portal_frame|flower_pot|bee_nest|armor_stand|item_frame|*minecart|*boat priority:100:
```

2020-11-03 00:51 UTC, BehrRiley approved these changes

2020-11-03 00:53 UTC, merged