Adding /BehrCraft command, usage/description, file cleanup.
BehrRiley/network-script-data pull request #79
Opened 2020-09-07 05:38 UTC by Eutherin

1. Added /BehrCraft and /bc alias, as well as reportlag 
2. Added usage/description to the following commands:
  - Survival
  - Hub
  - Lag_Report
3. Performed File cleanup in `behrcraft/repo-link/Structure/Formatting and Script Addons/`

2020-09-07 16:01 UTC, BehrRiley requested changes
confused about what `slime_puddle_creator` is made for; the suggested changes there only correct what's within the script as it stands if `<context.entity>` were valid, but it has no `events` key or a valid event header. See my comment on the script container itself for details there - but the `player_slime_block_break_handler` script container makes sense in what it was supposed to do with what we talked about in discord, i suggested the changes that would resolve what's wrong with that.

2020-09-07 19:09 UTC, Eutherin commented on denizen_scripts/global/server/commands/play.dsc
> +  - adjust <player> send_to:behrcraft
Gotcha sorry I missed that.

2020-09-07 20:04 UTC, Eutherin commented on denizen_scripts/survival/repo-link/MobScripts/SlimeStuff.dsc
> +    - flag server blocks_to_remove.<[Puddle_Location].simple>:<[Puddle_Location].material>
I thought that there was a remove flag command after modifyblock but see now it's missing. Thank you.

2020-09-07 20:06 UTC, Eutherin commented
> confused about what `slime_puddle_creator` is made for; the suggested changes there only correct what's within the script as it stands if `<context.entity>` were valid, but it has no `events` key or a valid event header.

Per some discord comments, the script is meant to be called up by a mythicmob, would that not provide a valid context.entity for the script? It seemed easier than looping the script indefinitely every x ticks.

2020-09-07 20:15 UTC, BehrRiley commented
> `Per some discord comments, the script is meant to be called up by a mythicmob, would that not provide a valid context.entity for the script?`

no

> `It seemed lighter than looping the script indefinitely every x ticks, or say an 'on entity moves' script.`

I'm not sure which would be heavier; but the former would likely be heavy depending on the number of slimes pathfinding, which includes if a player sets up a mob farm. this also raises the concern for verifying they're only converting solid blocks they step on, as opposed to literally everything always, like a stairway to heaven.

2020-09-08 05:51 UTC, BehrRiley commented on denizen_scripts/global/server/commands/play.dsc
> +  - adjust <player> send_to:behrcraft
new line at the end of the file is good here
```suggestion
  - adjust <player> send_to:behrcraft

```

2020-09-08 05:52 UTC, BehrRiley commented on denizen_scripts/global/server/commands/play.dsc
> +  alias:
`alias` should be `aliases`
```suggestion
  aliases:
```

2020-09-08 05:52 UTC, BehrRiley commented on denizen_scripts/global/server/commands/report_lag.dsc
> +  Alias:
`alias` should be `aliases`
```suggestion
  aliases:
```

2020-09-08 05:53 UTC, BehrRiley commented on denizen_scripts/survival/repo-link/MobScripts/SlimeStuff.dsc
> +    - playsound <context.location> sound:BLOCK_SLIME_BLOCK_BREAK
world script containers use `events`, not `script`
there also should be indention after the data key
```suggestion
  events:
    on player breaks:slime_block
      - if <server.has_flag[blocks_to_remove.<[context.location].simple>]>:
        - modifyblock <[Puddle_Location]> <server.flag[blocks_to_remove.<[<[Puddle_Location]>].simple>].as_material>
        - playeffect effect:BLOCK_CRACK at:<context.location> special_data:SLIME_BLOCK quantity:20
        - playsound <context.location> sound:BLOCK_SLIME_BLOCK_BREAK
```

2020-09-08 06:27 UTC, BehrRiley commented on denizen_scripts/survival/repo-link/MobScripts/SlimeStuff.dsc
> +  type: world
this should be a task for now
```suggestion
  type: task
```

2020-09-08 17:05 UTC, BehrRiley approved these changes

2020-09-08 17:07 UTC, merged